{%set name = "keystoneauth1" %}
{%set version = "2.19.0" %}
{%set hash_type = "sha256" %}
{%set hash_val = "1a249d6f2413195a86478a3de774a27b11798b4a477eb1e8217d8e40b89bfcfe" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pbr >=1.8

  run:
    - python
    - pbr >=1.8
    - iso8601 >=0.1.11
    - positional >=1.0.1
    - requests >=2.10.0
    - six >=1.9.0
    - stevedore >=1.10.0

test:
  imports:
    - keystoneauth1
    - keystoneauth1.identity
    - keystoneauth1.identity.v2
    - keystoneauth1.identity.v3
    - keystoneauth1.identity.generic
    - keystoneauth1.extras

about:
  home: http://docs.openstack.org/developer/keystoneauth/
  license: Apache 2.0
  license_family: Apache
  summary: 'Authentication Library for OpenStack Identity'

extra:
  recipe-maintainers:
    - pmlandwehr
