{% set name = "keystoneauth1" %}
{% set version = "3.4.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "9f1565eb261677e6d726c1323ce8ed8da3e1b0f70e9cee14f094ebd03fbeb328" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - pbr !=2.1.0,>=2.0.0

  run:
    - python
    - pbr !=2.1.0,>=2.0.0
    - iso8601 >=0.1.11
    - positional >=1.1.1
    - requests >=2.14.2
    - six >=1.10.0
    - stevedore >=1.20.0
    
test:
  imports:
    - keystoneauth1
    - keystoneauth1.identity
    - keystoneauth1.identity.v2
    - keystoneauth1.identity.v3
    - keystoneauth1.identity.generic
    - keystoneauth1.extras

about:
  home: https://docs.openstack.org/developer/keystoneauth/
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: Authentication Library for OpenStack Identity
  dev_url: https://git.openstack.org/cgit/openstack/keystoneauth
  doc_url: https://docs.openstack.org/developer/keystoneauth/

extra:
  recipe-maintainers:
    - pmlandwehr
