# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "xwKmeHqYauRBG3tRwUSKEa/5/gxM3zIZPEHpieSpELw1Xdbjt6ALirsFbCbgSCz1pUfJH31mQ8g04uV1Luysd2873ZEgMG5lgYfp15vw/nJ89Lxsa515I7HzJjnpj8eBWdXAWl1mi7Kab6atpFBK4VZIGCCb5hH3q2zdr2uZ8oktBnSAhE8/bOEN3SdmjvQqWWRhKg2L352gWc4t/9YN90BwUMCwBbJiVEZYl5utyaP+8hn8gtlhvMDbBJJ4X6FDb1nNhS41bwMHRnfvLlU60pG4+/3BPFVPh1JxvQfr7ktCtSCDeF0Sm+uOUDDUcGInGL2Z72qjgF/AVIpuxhS3QvfFUR9fnQBwwIUXTIQajxV4zfgq6l5BkxMCHt8wlo5c14bMfvGO7KD6v/yMksnrGz4Sa/kbywVUbWm/DJymcETz6Rg5Si2jT9PN9ofzjpCygAF0eT+w5DLV/9jAAH1on+lAEfmui16tVNS9QwJbN+UpJvNeW2Y90xMF7X4BM/zbQh8ix447zJHa+VRWhKNkmNYgqxzFqN85xhHsLKfyjP8E0dD9gBa6nImeqhPuDbRCXhmNtlRI5i4IKd672fUARmMbk6MvAzaTSIVFeJIVgIHH29PPefMtQKP+I2M+NaCdzmYlzLjWgEJrdPWAByVp+EUp7tg/QD/sV+2zdkd2FL8="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
