travis:
  secure:
    BINSTAR_TOKEN: ICvNHnA2ovoqq+txdy4rVKP1b+Uw+ZFfKhTqC8epcCB1yl7yMsLQ3DWW7ifpZTO3Sj09IX8ppTvzJNkXtP2zdVAtsiHEwrIsEg3gm7A5hKhvEhdqtwAdvf61lXY56pOEEHf2ooi6z9OZJUhdsOAOZseuxobXXSkE1hkXbkv6R/yxlSrJepFRrXmV9UenH3DeDiT24QRjM3sOT3JCuNido1VNKKTPYdrYgRchbvlR5K6jMi7A0HBoI8ayGMSpHLBkDsannB+HSTFVUreeXLxvhZTR00pRabFBH90KErYRp2qDKqO5a+jDLx6F1+Wqg6QCZotRHY35dbTQF8DZc2O2js/zF3LdW2LO77G1GtMjmXMRrr4cIvKN7GI5g0AHKBI2LXRDLNgry7O85eh0iocV+VyMkD1WLxNp7k+xhboRTRVh4qF/GeY62MuuFLpf3EA74aataBYE2raetNPpMSM9ntS8rZaZ9f0MxvzXh1QvaSI7+2Cd8o5sTe7XGIUUF05f7/JCeUerywVQ7s/YsIw3+iYiZTaNagovw7mJ7oIHzYPzFDnK0FBTKfSJj0+Y9tVW4aCdaPrc1dW6xejeFH4NGG/isAXzPuJ8ccchFIjuNumc/iTfEjNHNLJuuCKhxiGoAvOQFZ1xZNbWeW1ayd7MZ/MlTjHxg+zhVMYzjfWx9yY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
