travis:
  secure:
    BINSTAR_TOKEN: tkEJO8i25qf6I529HEsAQOjpPmnA7bEvSS2pOoaxSA44FxlweMCrYiSrIG8EeB9Kv5G0wm1ZqEmAOny5JQSedzb+wFOXLmJMhxngh7Z2pJ3MiaCbcUx57d+BHooSKBLFX5qiRSWy8FmDthFdOS4pDA9nf2wko+pqYg/wp3+wPvv7DW4gJAjPUhN2CT9/kUBVDmFMTXmSwUfTDeQ829LuaNsnO7tN65F06HXDa9qXTcXC4NOQlg6SXPJZ14/DGgeyzOO4hG8P7FFWmwbPsGS0uKd6h7R7BMGD6TPW90tJNx/Cq1jWC6KMpP04uUMP4jkR521KdgfMvH6CDYJJPYiVBdSDZk8qN2qfNWc6WPSos0SMtQDIwFrUAtG/4HNhJbyDD5PiaQuRonLUxWQiG+1e5jQD6T729cZiW3IIBI6xItZiYopkQoYuEAVy9rrN/5Sh9lvOTBtJhys12DP1o35wn28UqtMSZ1TsjeY4brbOCbSBfrID3u6tCzvO/6p6eCQMIYerEn8JDz3AsSof2F5Mi+/cTNMzX/hu+4bBbIc+LohvenlD+eUlazax7nqdTOWgr+laZ54ajyzm0TzRRnnHzA8c5yTmucaACyHMf6gfqDkbtVifWZEJAi0TICrXFnCDmpyXPb1H4rHiOvqbUgu2VmZQ8UIGecHvvso+HbhhJzc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
