travis:
  secure:
    BINSTAR_TOKEN: xwKmeHqYauRBG3tRwUSKEa/5/gxM3zIZPEHpieSpELw1Xdbjt6ALirsFbCbgSCz1pUfJH31mQ8g04uV1Luysd2873ZEgMG5lgYfp15vw/nJ89Lxsa515I7HzJjnpj8eBWdXAWl1mi7Kab6atpFBK4VZIGCCb5hH3q2zdr2uZ8oktBnSAhE8/bOEN3SdmjvQqWWRhKg2L352gWc4t/9YN90BwUMCwBbJiVEZYl5utyaP+8hn8gtlhvMDbBJJ4X6FDb1nNhS41bwMHRnfvLlU60pG4+/3BPFVPh1JxvQfr7ktCtSCDeF0Sm+uOUDDUcGInGL2Z72qjgF/AVIpuxhS3QvfFUR9fnQBwwIUXTIQajxV4zfgq6l5BkxMCHt8wlo5c14bMfvGO7KD6v/yMksnrGz4Sa/kbywVUbWm/DJymcETz6Rg5Si2jT9PN9ofzjpCygAF0eT+w5DLV/9jAAH1on+lAEfmui16tVNS9QwJbN+UpJvNeW2Y90xMF7X4BM/zbQh8ix447zJHa+VRWhKNkmNYgqxzFqN85xhHsLKfyjP8E0dD9gBa6nImeqhPuDbRCXhmNtlRI5i4IKd672fUARmMbk6MvAzaTSIVFeJIVgIHH29PPefMtQKP+I2M+NaCdzmYlzLjWgEJrdPWAByVp+EUp7tg/QD/sV+2zdkd2FL8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
