travis:
  secure:
    BINSTAR_TOKEN: EU3rKdgMB/qzD7Z6KxLFmutWA+19D46yrPgP7JfnAZVXkfdWzgPwinb83MbHNNPTgOUamQhrjfDwsLc+7O416Y102l+2mgXIgNxRhpcPVfX4M1zaPnHhxHnd8NCV+lIKdoED++zOGCTZaq+nGrFQxO41Ru46WDRvsHCxN8NkerG5S8rtOWqRPpxfPgDH1gajrpFYAVPFC6g5sWiampf+EvWrHlrX6qWlLr9N/C3NBNz3DKcVmjofwIjPifek2rs8+P0DR7BnYIv6fpc9E0nygVjdFtFKS7pyZP9C7nf1yY7uMuLbwEyQdExDiCFBSljPydK1zLnGneG47JGBW8pb43YJmjYz8/7Hz0YOWIrj9EUvnV+TLZmuJXkzUxCE1/KL2HU+U+ddZKWsIy1waLXH2LajouokMoFr6yKiR3waXmtXvMU4I7HQi61WDa7Q4c+JUYHG5bjsJ1SeIUplJXUOqNvelHDp+CxzIyQ1UV7nAin6sewOm/cxE8rNT2BZEXyF/PInUfwf3MYh5fGRsKFRUMRKdr9G6ltdLbUVPGHWDsk1loAVk0JF2odXsVa5EpV3WMmupYnbjpS48BRy+2HoGgHvhMmAFQuLiXz10SqfwiAyK8FsuA07tZluh32aaikM1J0p6cEFayzw153Wv8Dkg0aU6Elg/lRlER7v8szltCQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
