travis:
  secure:
    BINSTAR_TOKEN: DvElW6xdd0h516xLr6/YMREOtdgR07T4TxGMf8DUHUKvbMvollL1dK1MOxrtQwTee0gGPrMyOi/ObAoHp0cyh6miIj4xezApovrIN2kTRJHukXThBXFm1VL6nL5MjAPtVhhaBewxuGvoYRUfkskH/ChfC32SLJCDwreoC0LE92FGHz3F1g1dNJaNfZuzFW28fQrbeCL66UtEiw3z7/2CrEZ5mm7iMnrb1cwE00hJfbCuE0lJotDKIf3nW/pY7JqzPUVWLuzI5yam5/37iWVXdWKr25TUgmmxTdDO5BYlnutCYep741xW7eQxbe3uX+Vh1WD8s++EEdb3/nMhjJHkktVfNClJVSYhHoCM+O7T0R0v7zRhMPfbsCW0TpGZ7NHeleyt87FB+u4kfgf0w6T02ew39AJ9LXxO65fYrHzFMjobwdsaaTrCE/ktLlhJMM+OguTVodz6Dd+Cswk/CtdvY/UvW1DJsT24im6eRLwhILSdlio6p1UYahmZkJ47AjxtnKYZwLz2h9QUQPvaqryxCm/4WuH1dDrygKoNIB4SrU32O/2GcE3CI0suI60I3NhUC5qQcJOROWhUZcNKvj08XS5pHSXXKCpfjJmCSEy6/2O8+FU103K2S8N3FzRsxj00ozYKZ36RYTxC5nSWoQzA2oMOK5TeHKiNQ9W44mYphqw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
