travis:
  secure:
    BINSTAR_TOKEN: h5mYwPJJi1/O+T2MNvednap4a5hG5+fq06S6AA+KTVnMXbMMyMo0vuq7AKrYp9b8TBS5wDJdBIUy6XBInw+h+GacO16etr75Jo13o9gprkgQabh797CdicXkO3wES2fYydX83vk0ak9ncleCKcrp8eUpkFzW0QT0XnYK0oX9nI1fhgNlHAislB3varL7mTe6TugotceMG+MmjVUlMVa1PQRMnCraX9d1jyYWIAxQGCpHE1UyCocWWUlkrrhBX4z72QG5qtwuvZqM8VaBphtUiNwtkhD5mkz45UVfn2qTeBKDVJD7VEqB5xmufyidV4D1t5tmKN0DlWA+H62Wc6eICLCoxGkAGjQzdxzCclG+JH/0PO7BDsaJ3HP5FBTm6Ufda73J8i3eFmwyA1YAMMpj1wDqsG3hXhOoXojkpkciO0lNvTuyh2A4taUu05Kz+I/A7DO/ZqaTrBloFmKL72dUzujG4fgTLstn0JeYOZeKUvy9Zg3gm8oX7DiKhhKEd5iOS1hlz/SGxBbnNFBtobp5qhARF2WdLWHwhxTfPGClNFnWA8EwKiBlCJVzZT2AcYeIqRUdDYBD1Vj8nMYr2lbo02n/4pYrpCP1vJ9qlZRf5WoWkdJ2CMGkoGvliint/yV5bnCI/CtBIGE/aQy0QXJpexvkr7ltww+AhKovt8ExV+4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
