travis:
  secure:
    BINSTAR_TOKEN: LbBoOUkJDV/+s/FC2CWfkOmeyi8vtBFeEMDkELESbX3u14Zi4t8SczlrL+5QJJ/bgbtU3E3zyCSZ79kZW0TfndSzlJ+FGR8sb8bbMcs9YHVxqKtXj3VbKfYKJFtOKXUWJpknJ0+sWGg13+HLiwbJBUwAz843TeuBu1aK6oRssaFcosB65CpGHMsDDhGrmYZ2Ig10VmrssQGYOZZI/j1Upxy+GzlRGOclxrNlk2QVF5VIpcoyo4sjpzjkz8U1nOAECM5nHIugb8DFFqGhdtxmFLMLb0iPevYPhix1eIaeneYh4Q6gHPBilAZQNFqVqhox6x5D16fQ4t75zRcwqQ4uviFZ12Xo56iJkpHXfurqVWND0fXlGX8FdQW2ZIca9mfSpFarmQEVnJKPajX3VaiithSFM4kFeKsRm6adBqFmsg8wfsx/NH9Ya0G30OroiknXa9sqq4VyfTqkXqPYsrqAjRT74wRG8fw2ZbWr6aZ0wmmmaNGKpxmi5cfyimmxWmYJnVCijcFfez8VcX6EcgLi41riTXgUF8uctNIWpFcvyWHveseDRE4ClIyycH2aQvO+AwJ1Emjl27pOKf/ry3uIV0gLubxfROG0LFEs1I/MczRO7E/RKT2dnyNo8gwUIM+ARAuN7+srbuAjMo0uBhQz/AUHQZ5fFvkhpCi6WyPJQ+Q=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
