travis:
  secure:
    BINSTAR_TOKEN: Plj2LXwJuluKZwsGy9PS/fUOc8+EahkpxwcZDcjhV8UHQ2AnJqcYSo47VWOd4jtPeaxUIuVswqUOBQv1ybWXiUPO/t9V/KG2cR//XY2aNinb+11+zNZ18217nBC55d/khoYElR7TmTTguytAvt6DmEJpE/MfbqFpkEnMagv5E3pInFUUXkNIpUrpxaK8mfK42f4tp3iU0Nz36b4fWLQeWKZu1zgHDDh+HKE6qOJB/lkC9ughGbHiB19x/kZ0fPtA7d9yPABlM3ye53kLA3dL2C6jXB9bx+ocXXnX+LPq+/f5FkY+mnuDzod5CjiD3xSWPGvbPb6x8gIpkfRP+vIMx99fu5chAm6IE7nqLKG0ClYRKYQHTeaXpmHen0G2rVaLFenPR/gKuMp1QI4rr62Swe4bfuKlNMsgB98Ss98ggIRppkGpIrcdXz1g8YqZRBbifCPyCXJsq4Tz7ZlVaOELmgzGnMfwTOZS1ei5nyhDY0liH880lhfpgt/PXwEmaXYQ50Bhmq2iDMFoE25gWw08EJ1Yjic5B3pSr0vkfgA4Qmy8ZTYoglyzGINL3tEHq5xtmfAnkDRAYU0EEeXWBABmDvORuKo33wVMpir+ur06d0eZt0akso5WhQwIiOOWVS8y+v/jdTAQuwxuB0A2+HE53MWjaAJdsxrZnGOlAH80m80=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
