travis:
  secure:
    BINSTAR_TOKEN: QKKLPAS0vmbbFxhQyEjnij6bPoYxpB/ifVEKrdWImL4XXPALc+Vf3fbkQvoHL5dk+e7LnkoiuEThHYVaL6fjtki40PHD9n99tC6Ob9LUoxr/ARTWh52ZFFiNF0lIzWdsqGc0gzd9b7Xc34lhePEZznoYcDPzsKnepbGFw5rOG73UZkJoYZT6aApBg4qEdM2lT3QDuii6gVA7mvh8pcb5UxuyqkpOD+H4nOKXYnHOvnGA2DuSYWJjXEAL4TlNKLtinblsaKnZCwL62IkcRylKN3LEN19o1Jp0zH4WbYARj/xhtoQRlxd5SVu9k4TZPovvoRXV+KYT/qoPqDK3L9JL64PFQ2hZqm+v5cHXl8iDXGj8RuY4jKyMSTK+HVT9NNl5X1b3anXO/Z5iRr5nzTNKez1MEU7ndpI7zteZVnrn3gB3+Cpe8XRk5ulDStC+fFiChPe+PH4uUmI5icLgK7VSIocSWG7K+b9bAwvmFVumSRSpd8zp9XaZtg05/MZVsRaJMMTfkOOruk2xtgWcpVshyKHsJECOfAGVt7HkAwv5nMobuQCVfL3Nrl/P8J/4b1/w6kPJCCVrgUOIZjrCbd7z+t6z6c8bbqPmLAMWblUXWrKqQnlkEuNr4l+in27hUzFh4Wg4Hll9zH5z7sEdp8Nv2mq5zFd/0UJUkL2EUdMcZeI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
